name: '15gifts ECS Check Latest Deployments'
description: 'Ensures the latest ECS deployment was successful'
author: '15gifts'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  ecs-cluster:
    description: 'The name of the ECS cluster to deploy to'
    required: true
  ecs-service:
    description: 'The name of the ECS service to deploy to'
    required: true
  aws-region:
    description: 'The AWS region where the ECS cluster is located (e.g., us-east-1).'
    required: true

runs:
  using: node20
  main: dist/index.js